# getAllStudentsByCourseId
GET http://localhost:8000/api/course/1/getAllStudents HTTP/1.1

# getAllStudentsByCourseId
###
GET http://localhost:8000/api/course/1/addStudent/1 HTTP/1.1

###
# getAllCourses
GET http://localhost:8000/api/admin/getAllCourses HTTP/1.1


###
# add a course

GET  http://localhost:8000/api/teacher/11/getTeachingCourses HTTP/1.1
Content-Type: application/json



###
POST http://localhost:8000/api/teacher/addAnnouncement HTTP/1.1
Content-Type: application/json

{
    "title":"Test title", 
    "content":"student should finished hw1 before next Monday", 
    "course_id": 6
}
###
POST http://localhost:8000/api/admin/addCourse HTTP/1.1
Content-Type: application/json

{
    "name":"test Course", 
    "description":"haha", 
    "capacity": 10, 
    "teacher_id": 1
}

###

POST  http://localhost:8000/api/register HTTP/1.1

Content-Type: application/json

{
    "name" :"admin", 
    "email": "admin@admin.com",
    "password": "password",
    "role": "admin",
    "isActive": "true"
}

###
#get announcements of a course
GET http://localhost:8000/api/course/1/announcements HTTP/1.1
Content-Type: application/json


###
#get assignments of a course
GET http://localhost:8000/api/course/6/assignments HTTP/1.1
Content-Type: application/json


###
#add assignment
POST http://localhost:8000/api/course/assignments HTTP/1.1
Content-Type: application/json

{
    "course_id" : 6,
    "title": "assign1",
    "description": "des",
    "due_date": "Mon May 23 2022 00:00:00 GMT-0500 (Central Daylight Time)",
    "max_points": 100
}


###get a student's all announcements
GET http://localhost:8000/api/student/6/announcements HTTP/1.1
Content-Type: application/json

###get a student's all courses
GET http://localhost:8000/api/student/6/courses HTTP/1.1
Content-Type: application/json