
GET  http://localhost:8000/api/teacher/11/getTeachingCourses HTTP/1.1
Content-Type: application/json



###
POST http://localhost:8000/api/teacher/addAnnouncement HTTP/1.1
Content-Type: application/json

{
    "title":"Test title", 
    "content":"student should finished hw1 before next Monday", 
    "course_id": 6
}
###
POST http://localhost:8000/api/admin/addCourse HTTP/1.1
Content-Type: application/json

{
    "name":"test Course", 
    "description":"haha", 
    "capacity": 10, 
    "teacher_id": 1
}

###
GET http://localhost:8000/api/course/1/announcements HTTP/1.1
Content-Type: application/json


###
GET http://localhost:8000/api/course/6/assignments HTTP/1.1
Content-Type: application/json


###
#add assignment
POST http://localhost:8000/api/course/assignments HTTP/1.1
Content-Type: application/json

{
    "course_id" : 6,
    "title": "assign1",
    "description": "des",
    "due_date": "5/19/2022",
    "max_points": 100
}